// Generated by CoffeeScript 1.6.2
(function() {
  var client, socket;

  client = require('socket.io-client');

  socket = client.connect('http://localhost:30001');

  socket.on('news', function(data) {
    console.log(data);
    return socket.emit('my other event', {
      my: 'data'
    });
  });

}).call(this);
