// Generated by CoffeeScript 1.6.2
(function() {
  var EventEmitter, Robot, app;

  app = require('express.io');

  EventEmitter = require.EventEmitter;

  Robot = (function() {
    function Robot(name) {
      if (name == null) {
        name = "flyio";
      }
      this.name = name;
      this.events = new EventEmitter;
      this.app = app();
    }

    Robot.prototype.init = function() {};

    Robot.prototype.initExpress = function() {
      app.set('views', __dirname + '/../views');
      return app.get('/', function(req, res) {
        return res.sendfile(__dirname + '/../views/index.html');
      });
    };

    Robot.prototype.listen = function() {};

    return Robot;

  })();

}).call(this);
