// Generated by CoffeeScript 1.6.2
(function() {
  var EventEmitter, Robot;

  EventEmitter = require.EventEmitter;

  Robot = (function() {
    function Robot(name) {
      if (name == null) {
        name = "flyio";
      }
      this.name = name;
      this.events = new EventEmitter;
    }

    return Robot;

  })();

}).call(this);
