// Generated by CoffeeScript 1.6.2
(function() {
  var Moniker, User,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Moniker = require('moniker');

  User = (function() {
    function User() {
      this.users = {};
    }

    User.prototype.addUser = function() {
      var name, user;

      name = Moniker.choose();
      user = {
        name: name,
        clicks: 0
      };
      this.users[name] = user;
      this.updateUsers();
      return user;
    };

    User.prototype.removeUser = function(user) {
      var _ref;

      if (_ref = user.name, __indexOf.call(this.users, _ref) >= 0) {
        delete this.users[user.name];
      }
      return user;
    };

    User.prototype.updateUsers = function(callback) {
      var str, user;

      str = '';
      for (user in this.users) {
        str += user.name + ' <small>(' + user.clicks + ' clicks)</small>';
      }
      if (callback) {
        return callback(str);
      }
    };

    return User;

  })();

  module.exports = new User;

}).call(this);
