// Generated by CoffeeScript 1.6.2
(function() {
  var assert, options, vfs;

  assert = require("assert");

  options = {
    root: "/"
  };

  vfs = require("vfs-local")(options);

  module.exports = vfs;

}).call(this);
